show_drafts: true
future: true
unpublished:

my:
  domain: stage.serverless.industries
  sitetitle: "[Stage] Serverless Industries"
  rsstitle: "[Stage] Serverless Industries Posts RSS"
  env: stage
  webmention_endpoint: null
  pingback_endpoint: null
  micropub_endpoint: null
  authorization_endpoint: null
  token_endpoint: null
  metadata_endpoint: null

url: "https://stage.serverless.industries"
