markdown_ext: "md,markdown"
show_drafts: false
future: false
unpublished: false
timezone: Europe/Berlin

my:
  domain: serverless.industries
  sitetitle: Serverless Industries
  rsstitle: Serverless Industries Posts RSS
  env: live

title: serverless.industries
url: "https://serverless.industries"

include: [ ".well-known", ".htaccess" ]

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: "_posts/guides"
      type: "posts"
    values:
      layout: "guide"
      permalink: /guides/:title:output_ext
      toc: true
      posttype: guide
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title:output_ext
      posttype: post
  - scope:
      path: ""
      type: tags
    values:
      layout: tagpage
      permalink: tag/:tagname:output_ext

langmap:
  en: { name: English, intname: English, postlist: "Articles in English" }
  de: { name: Deutsch, intname: German, postlist: "Beiträge in Deutsch" }

posttypemap:
  post: { name: Article }
  guide: { name: Guide }

plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-toc
  - jekyll-paginate-v2

target-blank:
  noopener: false
  noreferrer: false

collections:
  authors:
    output: true
  projects:
    output: true

pagination:
  enabled: true
  per_page: 24
  sort_field: 'date'
  sort_reverse: true
  title: ':title - Page :num'
  permalink: '/:num/'

feed:
  post_limit: 20
  categories:
    - frontpage
    - language-de
    - language-en
