markdown_ext: "md,markdown"
show_drafts: false
future: false
unpublished: false
timezone: Europe/Berlin

# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:year/:month/:day/:title:output_ext

my:
  domain: serverless.industries
  sitetitle: Serverless Industries
  rsstitle: Serverless Industries Posts RSS
  env: live

title: serverless.industries
url: "https://serverless.industries"

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

langmap:
  en: English
  de: Deutsch

plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-toc

collections:
  authors:
    title: Authors
    output: true
