git:
    isci: '__is_ci__'
    enableserviceworker: '__serviceworker_enabled__'
    commiturl: "https://github.com/perryflynn/serverless.industries/commit/__commit_long__"
    commitshort: "__commit_short__"
    commitlong: "__commit_long__"
    committs: "__commit_timestamp__"
